FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy source
COPY . .

# Expose port
EXPOSE 3000

# Start in development mode
CMD ["yarn", "dev"]
